remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "База знаний для .NET разработчика"
description: "В данном проекте собранны основыне понятия, необходимые для разработки и собеседований"
