theme: minima
plugins:
  - jekyll-feed
minima:
  skin: dark
title: "База знаний для .NET разработчика"
description: "В данном проекте собранны основыне понятия, необходимые для разработки и собеседований"
